feat(contribution-types.js): add research contribution type
all-contributors/all-contributors-cli pull request #291
Opened 2020-10-08 18:07 UTC by LaChapeliere

**What**:
Add a research contribution type with microscope emoji, for people doing literature review, code
prototyping or any other research-related activity.

Part 2/3 of #446

**Why**:
For open science projects or dev projects with a research component, people carrying out research tasks cannot always be acknowledged with the existing types.

Adding the type description and emoji to the list of types available to the CLI tool.

**Checklist**:
- [x] Documentation
- [ ] Tests
- [ ] Ready to be merged
- [ ] Added myself to contributors table

I'm not really familiar with npm so I'm not sure how to install my modified version of the cli tool to test it. Any help?

2020-10-08 22:43 UTC, Berkmann18 requested changes

2020-10-08 22:43 UTC, Berkmann18 commented on src/util/contribution-types.js
> +      symbol: ':microscope:',
```suggestion
      symbol: '🔬',
```

2020-10-09 18:34 UTC, Berkmann18 approved these changes

2020-10-09 18:34 UTC, merged

2020-10-09 18:34 UTC, Berkmann18 commented
@all-contributors Please add @LaChapeliere for code

2020-10-22 10:15 UTC, blackguard88 commented
✨ 📦🚀

2020-10-22 10:16 UTC, blackguard88 commented
@LaChapeliere

2020-10-22 10:18 UTC, blackguard88 reviewed
@blackguard88